# Generated by Django 4.1.5 on 2023-02-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_choices_answer_rename_choice_answer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Multiple Choices', 'Multiple Choices'), ('True or False', 'True or False'), ('Free Text', 'Free Text')], max_length=200),
        ),
    ]
