# Generated by Django 4.1.5 on 2023-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_question_remove_country_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Administrator', 'Administrator')], default='Administrator', max_length=200),
            preserve_default=False,
        ),
    ]
